@startuml
'https://plantuml.com/class-diagram

interface Position {
    x: number;
    y: number;
}

class Sprite {
    position: Position
    width : number
    height : number
    scale : number

}

class fighter {

}



@enduml