@startuml
'https://plantuml.com/class-diagram


class Sprite {

}

class Player {

}

class Game {
}

class GameController {
}

class PadController {
}

Game o-- Player
Player --> PadController

Player --|> Sprite
PadController --|>  GameController

@enduml